---
title: "천안시 아파트"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: rows
    theme:
      bg: "#FFFFFF"
      fg: "#000000" 
      primary: "#7fcdff"
      base_font: 
        google: Prompt
        
---

```{r, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library("highcharter")
```

```{python, include = FALSE}
import pandas as pd
import geopandas as gpd
from folium import Marker,GeoJson,Choropleth,Circle
from folium.plugins import BeautifyIcon
import folium
import warnings 
warnings.filterwarnings('ignore')
from geopy.geocoders import Nominatim

```

천안시 아파트의 분포
======


Row {.sidebar data-width=1410}
-----------
### 아파트 위치
```{python}
apt_path = "https://raw.githubusercontent.com/Sungileo/trainsets_2/main/apartment_latlon.csv"

apt_raw = pd.read_csv(apt_path)
apt_latlon = apt_raw.iloc[:,2:5]

apt_latlon_gdf = gpd.GeoDataFrame(apt_latlon, geometry=gpd.points_from_xy(apt_latlon['lon'], apt_latlon['lat']))
```
```{python, include = FALSE}
m = folium.Map(location=[36.807438,127.144504], zoom_start=13)

for idx, row in apt_latlon_gdf.iterrows():
    Marker(location = [row['lat'], row['lon']],
           popup=row["아파트"]).add_to(m)
```

```{python}
m
```


Row {data-height=350}
-----------
### 천안시 아파트의 건축년도 분포
```{r, include = FALSE}
library(plotly)

data_path = "https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EC%B2%9C%EC%95%88%EC%8B%9C_%EC%95%84%ED%8C%8C%ED%8A%B8_%EB%A7%A4%EB%A7%A4_2018_2023.csv"

data_raw = read.csv(data_path,row.names = 1)
data_use = data_raw %>% select(c(5,6,8,12))

data_dev <- data_use %>% 
  group_by(아파트) %>% 
  summarize(거래금액평균 = round(mean(거래금액)), 
            건축년도 = round(mean(건축년도)))

```

```{r}
hcboxplot(x=data_dev$건축년도, name = "건축년도") %>% 
  hc_chart(type="column")%>%
  hc_title(text = "건축년도 분포")%>%
  hc_add_series(data = data_dev,
                type = "scatter",
                hcaes(x="0",y="data_dev$건축년도"),
                tooltip=list(
      pointFormat = "<b>{point.아파트}</b> <br/>건축년도 : {point.건축년도}<br/>"
    ))%>%
  hc_plotOptions(scatter = list(
    color = "grey40",
    marker = list(
      radius = 2,
      symbol = "circle",
      lineWidth = 1
    )
  ))  %>%
  hc_plotOptions(scatter = list(jitter = list(x = .1, y = 0)))

```


Row {data-height=350}
-----------
### 아파트별 평균 거래금액 분포
```{r}

hcboxplot(x=data_dev$거래금액평균, name = "거래금액평균") %>% 
  hc_chart(type="column")%>%
  hc_add_series(data = data_dev,
                type = "scatter",
                hcaes(x="0",y="data_dev$거래금액평균"),
                tooltip=list(
      pointFormat = "<b>{point.아파트}</b> <br/>거래금액평균(만원) : {point.거래금액평균}<br/>"
    ))%>%
  hc_plotOptions(scatter = list(
    color = "grey40",
    marker = list(
      radius = 2,
      symbol = "circle",
      lineWidth = 1
    )
  ))  %>%
  hc_plotOptions(scatter = list(jitter = list(x = .1, y = 0)))

```


천안시 학교의 분포
======


Row {.sidebar data-width=1410}
-----------
### 천안시 초, 중, 고등학교 위치
```{python}
elm_school = pd.read_csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EC%B4%88%EB%93%B1%ED%95%99%EA%B5%90%20%EC%9C%84%EA%B2%BD%EB%8F%84.csv")
mid_school = pd.read_csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EC%A4%91%ED%95%99%EA%B5%90_%EC%9C%84%EA%B2%BD%EB%8F%84.csv")
hi_school = pd.read_csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90_%EC%9C%84%EA%B2%BD%EB%8F%84.csv")

elm_school = gpd.GeoDataFrame(elm_school, geometry=gpd.points_from_xy(elm_school['Longitude'], elm_school['Latitude']))
mid_school = gpd.GeoDataFrame(mid_school, geometry=gpd.points_from_xy(mid_school['Longitude'], mid_school['Latitude']))
hi_school = gpd.GeoDataFrame(hi_school, geometry=gpd.points_from_xy(hi_school['Longitude'], hi_school['Latitude']))

elm_school.crs = 'EPSG:4326'
mid_school.crs = 'EPSG:4326'
hi_school.crs = 'EPSG:4326'

elm_school = elm_school.to_crs('EPSG:3857')
mid_school = mid_school.to_crs('EPSG:3857')
hi_school = hi_school.to_crs('EPSG:3857')
```

```{python, include = FALSE}
m_1 = folium.Map(location=[36.807438,127.144504], zoom_start=13)

folium.TileLayer('cartodbpositron').add_to(m_1)

icons_sq = []

for i in range(len(elm_school)):

    icon_name = f'icon_square_{i}'
    icon = BeautifyIcon(
        icon_shape='rectangle-dot',
        border_color='red',
        border_width=6
    )
    locals()[icon_name] = icon
    icons_sq.append(icon)

    folium.Marker(location=[elm_school.loc[i,"Latitude"],elm_school.loc[i,"Longitude"]],
                  tooltip=elm_school.loc[i,"초등학교"],icon=icons_sq[i]).add_to(m_1)

icons_c = []

for i in range(len(mid_school)):

    icon_name = f'icon_c_{i}'
    iconc = BeautifyIcon(
        icon_shape='circle-dot',
        border_color='blue',
        border_width=6
    )
    locals()[icon_name] = iconc
    icons_c.append(iconc)

    folium.Marker(location=[mid_school.loc[i,"Latitude"],mid_school.loc[i,"Longitude"]],
                  tooltip=mid_school.loc[i,"중학"],icon=icons_c[i]).add_to(m_1)




icons_st = []

for i in range(len(hi_school)):

    icon_name = f'icon_star_{i}'
    iconst = BeautifyIcon(
        icon_shape='triangle',
        inner_icon_style='color:green;font-size:20px;',
        background_color='transparent',
        border_color='transparent',
        border_width=6
    )
    locals()[icon_name] = iconst
    icons_st.append(iconst)

    folium.Marker(location=[hi_school.loc[i,"Latitude"],hi_school.loc[i,"Longitude"]],
                  tooltip=hi_school.loc[i,"고등학교"],icon=icons_st[i]).add_to(m_1)

```

```{python}
m_1
```

Row {.tabset data-height=350}
------
```{r}
elm_school = read.csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EC%B4%88%EB%93%B1%ED%95%99%EA%B5%90%20%EC%9C%84%EA%B2%BD%EB%8F%84.csv")
mid_school = read.csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EC%A4%91%ED%95%99%EA%B5%90_%EC%9C%84%EA%B2%BD%EB%8F%84.csv")
hi_school = read.csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90_%EC%9C%84%EA%B2%BD%EB%8F%84.csv")
```

### 초등학교 목록
```{r}
kable(elm_school$초등학교)
```


### 중학교 목록
```{r}
kable(mid_school$중학)
```

### 고등학교 목록
```{r}
kable(hi_school$고등학교)
```

Row {data-height-350}
-------

### 초등학교
```{r}
valueBox(77,color = "red")
```


### 중학교
```{r}
valueBox(31,color = "blue")
```

### 고등학교
```{r}
valueBox(21,color = "darkgreen")
```



동별 거래액
======


```{r, include = FALSE}
library(sf)
library(rgdal)
library(ggplot2)
library(dplyr)
```

```{r, include = FALSE}
data_sp <- readOGR("/home/sungil/dataset/LSMD_ADM_SECT_UMD_44.shp",encoding = "euc-kr")
data_sf <- st_as_sf(data_sp)

data_cheonan <- data_sf[data_sf$COL_ADM_SE==44130,]

library(tmap)
tmap_mode("view")
tmap_options(check.and.fix = TRUE)
```

```{r, include = FALSE}
data_path = "https://raw.githubusercontent.com/Sungileo/trainsets_2/main/%EC%B2%9C%EC%95%88%EC%8B%9C_%EC%95%84%ED%8C%8C%ED%8A%B8_%EB%A7%A4%EB%A7%A4_2018_2023.csv"

data_raw = read.csv(data_path,row.names = 1)
data_use = data_raw %>% select(c(5,6,8,12)) %>% mutate(평당거래액 = 거래금액/(전용면적/3.3058))

data_dev <- data_use %>% 
  group_by(아파트) %>% 
  summarize(평균평당거래액 = round(mean(평당거래액)),
            최고평당거래액 = round(max(평당거래액)),
            최저평당거래액 = round(min(평당거래액)))

data_2 <- read.csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/apartment_latlon.csv",row.names = 1)

data_join <- data_dev %>% left_join(data_2,by = "아파트")
data_join <- data_join %>% st_as_sf(coords = c("lon","lat"))
st_crs(data_join) <- 4737

data_cheonan_2 <- data_cheonan["EMD_NM"]
data_cheonan_2 <- st_transform(data_cheonan_2,4737)


data_cheonan_2 <- st_make_valid(data_cheonan_2)
#data_cheonan_2 %>% plot()

data_join %>%  st_crs()
geom_joined <- data_cheonan_2 %>% st_join(data_join,join = st_intersects)
geom_joined[is.na(geom_joined)] <- 0

data_avg <- geom_joined %>% 
  group_by(EMD_NM) %>% summarize(평균평당거래액 = round(mean(평균평당거래액)),
            최고평당거래액 = round(max(최고평당거래액)),
            최저평당거래액 = round(min(최저평당거래액)),
            geometry = first(geometry))

data_avg$평균평당거래액[data_avg$평균평당거래액 == 0] <- NA

```

```{r,include=FALSE}
tm_1 <- tm_shape(data_avg)+
  tm_polygons("평균평당거래액",
              popup.vars = c("평균평당거래액 (만원)" = "평균평당거래액","최고평당거래액 (만원)" = "최고평당거래액","최저평당거래액 (만원)" = "최저평당거래액"),
              n=7,
              colorNA = "grey90",
              alpha = 0.7)
```

Row {}
-----------
### 동별 거래액

```{python}
tm_1
```

